
server:
  protocol: http
  host: localhost
  port: 8088

admins:
  subs: []
  groups:
    - dabih

crypto:
  rootKeys: []

# Configure where to store temporary data
ephemeral:
  adapter: 'memory'

database:
  dialect: sqlite
  logging: false 
  storage: ./data/dabih.sqlite


storage:
  backend: local
  path: ./data 
