server:
  # delete this key to disable demo mode
  demo: YTgyZTEzZTI5YjNiZmUK 
  port: 8088

admins:
  subs: []
  groups:
    - dabih

crypto:
  rootKeys: []

# Configure where to store temporary data
ephemeral:
  adapter: memory

database:
  dialect: sqlite
  logging: false
  storage: ./data/dabih.sqlite

storage:
  backend: local
  path: ./data

